### PR TITLE
Fix write mode

### PR DESCRIPTION
**Pull request by AnthonyRyuki**
This fixes the bug that prevents write mode from working.

### CODE REVIEW

**Comment by AnthonyRyuki** [comment]
Oh, wait a minute. I think I figured out why it wasn't working on me: I always ran the write mode with the app in the same folder as the .ini and the other stuff. A bug prevents it from working that way, it only works when it's on a different folder, but the way the pull request is right now, it can only work when it's on the same folder. I think I should add an if statement for both conditions...

**Comment by AnthonyRyuki** [comment]
OK, now it works perfectly.

**Comment by xan1242** [comment]
Oh sorry I wasn't paying much attention to this project, sorry. (I swear any time I look at it I never have access to my main workstation lol)

I honestly don't know what I was on when I wrote those silly string operations...

In any case, I'll accept your PR, thank you very much!

**Comment by AnthonyRyuki** [comment]
No problem man.
Also, this project of yours proved to be quite helpful when I decided to do this: https://www.romhacking.net/hacks/6852/

**Pull request merged**
